### ISSUE TITLE
Missing metrics name

### ISSUE THREAD

**Issue by RDruon** [whamcloud/lustrefs-exporter#8]
Using Grafana and 2 already available dashboard https://grafana.com/grafana/dashboards/9658 and https://grafana.com/grafana/dashboards/9666 allows us to detect which metrics are missing or malformed.

Most of the queries rely on a label called `job` like `sum(rate(lustre_stats_total{component="mdt",job=~"$server.*"}[120s])) by (job)`, this label is set by the prometheus server (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).
This label is set using the `job_name` value in the prometheus server config file like
```
....
  - job_name: 'host1'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['192.168.1.1:32221']
  - job_name: 'host2'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['192.168.1.2:32221']
....
```

This ticket will be used to track missing metrics:

- [ ] lustre_free_kilobytes -> Rename existing `lustre_free_bytes`
- [ ] lustre_capacity_kilobytes -> Rename existing `lustre_capacity_bytes`
- [ ] `component` tag value needs to be lowercase instead of uppercase
